### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by cvladan** [qriouslad/admin-site-enhancements#10]
First of all I would like to thank you for an excellent plugin that I use regularly and have praised several times. I have a couple of suggestions for improvement.

1. When the "Hide Admin Notices" option is enabled and you go to "Notices" in the admin bar, you have to click with the mouse to bring up the panel. And that's fine. However, it's essential to add a hand cursor style to indicate to users that they need to click. I was waiting for it to hover, because that's how the admin menu usually works. So definitely add a hand cursor. Also, consider adding a setting for whether the menu should hover or click, or just use a value in seconds, so if it's 0 then it's click.

1. This is a suggestion for the description and demo of your plugin. I see that you have a lot of video in the description, and that's fine. However, wp.org plugins now allow you to include a demo link - called a "live preview". This is all done with blueprints - have a look at how it's done in the plugin "plugins/serbian-addons-for-woocommerce/". I think it's a very new thing, but it's excellent.

<img width="939" alt="image" src="https://github.com/qriouslad/admin-site-enhancements/assets/1913156/843c4e06-98bd-41a4-a46f-d167b6dade71">

---

If you accept these suggestions, as it would be the 3rd accepted suggestion, it would be nice if you could send me a Pro licence. Of course, you don't have to - I'll keep contributing anyway.

Please, just don't go overboard with the upselling, so as not to drive away some of the more experienced users.

**Comment by qriouslad** [comment]
@cvladan thanks for the suggestion. The first one will be implemented in the next release. I'll have to test out the second one, which I'm already aware of since the 'botched' deployment to .org repo the first time around. Please leave a message at https://www.wpase.com/ask/ so I have your email and can send you a free license. Thanks for all the feedback you've given so far!
