### ISSUE TITLE
Fatal Error Crash

### ISSUE THREAD

**Issue by cvladan** [qriouslad/admin-site-enhancements#12]
Please consider adding a check to see if writing to `wp-config.php` is possible, because on some hosts, such as this one ([https://raidboxes.io/](https://raidboxes.io/)), the `wp-config.php` file is locked, and I think this is a good practice. It's fine to modify it, but the code should be resilient to the fact that it can't be modified, so if it can't write to `wp-config.php`, it should simply report this instead of causing the site to crash.

```
PHP Warning:  file_put_contents(/home/wp/disk/wordpress/wp-config.php): Failed to open stream: Permission denied in /home/wp/disk/wordpress/wp-content/plugins/admin-site-enhancements/classes/class-wp-config-transformer.php on line 418

PHP Fatal error:  Uncaught Exception: Failed to update the config file. in /home/wp/disk/wordpress/wp-content/plugins/admin-site-enhancements/classes/class-wp-config-transformer.php:421
```

Once again - thank you for the excellent plugin.

**Comment by cvladan** [comment]
https://wordpress.org/support/topic/fatal-error-crash/#post-18050029

**Comment by qriouslad** [comment]
This will be resolved in the next release. Thanks for reporting @cvladan.
