### ISSUE TITLE
An idea for a small improvement

### ISSUE THREAD

**Issue by cvladan** [qriouslad/admin-site-enhancements#2]
I find the option to add an ID column to the list view excellently implemented and indispensable. Previously, I used a separate utility plugin for this purpose, of which there are, of course, many: [Reveal IDs](https://wordpress.org/plugins/reveal-ids-for-wp-admin-25/), [Show IDs by DraftPress](https://wordpress.org/plugins/wpsite-show-ids/), [Add ID Column](https://wordpress.org/plugins/add-id-column/), [LH Add ID Columns](https://wordpress.org/plugins/lh-add-id-columns/), [Show Pages IDs](https://wordpress.org/plugins/show-posts-and-pages-id/), etc.

However, there is one that was my favorite, and that is [Show IDs by Echo Plugins](https://wordpress.org/plugins/echo-show-ids/). Its main advantage is that the ID can be displayed in two places, next to the item and in the column. I exclusively display the ID next to the item, as it seems like a more logical location to me.

Therefore, I suggest that you also **implement the possibility to display the ID next to the item**.

Thank you in advance!

Furthermore, I would like to express my sincere gratitude for the effort you have put into creating this plugin.
Keep up the great work!

**Comment by qriouslad** [comment]
@cvladan thanks for the suggestion and kind words. It's been included in v4.7.4. Do try it out and let me know if it works as intended.

**Comment by qriouslad** [comment]
@cvladan I'm revisiting ASE's old(er) support threads to appreciate the feedback you've given in improving ASE with a sneak peak of, and discount code you can get for the soon-to-be-released Pro version of ASE. 

If you're interested, please contact me at [https://bowo.io/](https://bowo.io/) so I can send you the link to the website and the discount code.
